// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: app_user.sql

package models

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createNewAppUser = `-- name: CreateNewAppUser :one
INSERT INTO
    app_user (
        user_id,
        name,
        username,
        email,
        mobile,
        password_hash,
        oauth_client_id,
        updated_by
    )
VALUES (
        $1, -- id
        $2, -- Name
        $3, -- Username
        $4, -- Email
        $5, -- Mobile
        $6, -- Password Hash
        $7, -- OAuth Client ID
        $8 -- Updated By
    ) RETURNING user_id, oauth_client_id, username, profile_picture_url, bio, name, mobile, email, password_hash, last_login_at, updated_at, created_at, updated_by
`

type CreateNewAppUserParams struct {
	UserID        uuid.UUID
	Name          sql.NullString
	Username      sql.NullString
	Email         sql.NullString
	Mobile        sql.NullString
	PasswordHash  sql.NullString
	OauthClientID sql.NullString
	UpdatedBy     uuid.NullUUID
}

func (q *Queries) CreateNewAppUser(ctx context.Context, arg CreateNewAppUserParams) (AppUser, error) {
	row := q.db.QueryRowContext(ctx, createNewAppUser,
		arg.UserID,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Mobile,
		arg.PasswordHash,
		arg.OauthClientID,
		arg.UpdatedBy,
	)
	var i AppUser
	err := row.Scan(
		&i.UserID,
		&i.OauthClientID,
		&i.Username,
		&i.ProfilePictureUrl,
		&i.Bio,
		&i.Name,
		&i.Mobile,
		&i.Email,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateAppUserLastLoginAtByOAuthClientID = `-- name: UpdateAppUserLastLoginAtByOAuthClientID :one
UPDATE app_user
SET
    last_login_at = now()
WHERE
    oauth_client_id = $1 RETURNING user_id,
    username,
    profile_picture_url,
    bio,
    name,
    mobile,
    email,
    oauth_client_id,
    last_login_at,
    created_at,
    updated_at,
    updated_by
`

type UpdateAppUserLastLoginAtByOAuthClientIDRow struct {
	UserID            uuid.UUID
	Username          sql.NullString
	ProfilePictureUrl sql.NullString
	Bio               sql.NullString
	Name              sql.NullString
	Mobile            sql.NullString
	Email             sql.NullString
	OauthClientID     sql.NullString
	LastLoginAt       sql.NullTime
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	UpdatedBy         uuid.NullUUID
}

func (q *Queries) UpdateAppUserLastLoginAtByOAuthClientID(ctx context.Context, oauthClientID sql.NullString) (UpdateAppUserLastLoginAtByOAuthClientIDRow, error) {
	row := q.db.QueryRowContext(ctx, updateAppUserLastLoginAtByOAuthClientID, oauthClientID)
	var i UpdateAppUserLastLoginAtByOAuthClientIDRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.ProfilePictureUrl,
		&i.Bio,
		&i.Name,
		&i.Mobile,
		&i.Email,
		&i.OauthClientID,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
