// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: community.sql

package models

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createNewCommunity = `-- name: CreateNewCommunity :one
INSERT INTO community (title, about, thumbnail_url, logo_url, updated_by)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
) RETURNING id, title, about, thumbnail_url, logo_url, updated_at, created_at, updated_by
`

type CreateNewCommunityParams struct {
	Title        sql.NullString
	About        sql.NullString
	ThumbnailUrl sql.NullString
	LogoUrl      sql.NullString
	UpdatedBy    uuid.NullUUID
}

func (q *Queries) CreateNewCommunity(ctx context.Context, arg CreateNewCommunityParams) (Community, error) {
	row := q.db.QueryRowContext(ctx, createNewCommunity,
		arg.Title,
		arg.About,
		arg.ThumbnailUrl,
		arg.LogoUrl,
		arg.UpdatedBy,
	)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.About,
		&i.ThumbnailUrl,
		&i.LogoUrl,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
