// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: interest.sql

package models

import (
	"context"
)

const getAllInterest = `-- name: GetAllInterest :many
SELECT id, name, updated_at, created_at, updated_by FROM interest
`

func (q *Queries) GetAllInterest(ctx context.Context) ([]Interest, error) {
	rows, err := q.db.QueryContext(ctx, getAllInterest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Interest
	for rows.Next() {
		var i Interest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
