name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mindo-server:latest

      - name: Verify Pushed Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/mindo-server:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Log into Docker on EC2 instance
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_KEY }}

            # Pull the latest Docker image from Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/mindo-server:latest

            # Stop and remove any existing containers with the same name
            sudo docker stop mindo-server || true
            sudo docker rm mindo-server || true

            # Run the container on EC2, passing in the necessary environment variables
            sudo docker run -d \
              --name mindo-server \
              --restart=unless-stopped \
              -p ${{ vars.APP_PORT }}:${{ vars.APP_PORT }} \
              -e ENV=${{ vars.ENV }} \
              -e APP_PORT=${{ vars.APP_PORT }} \
              -e DB_URI=${{ secrets.DB_URI }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
              -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              -e YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }} \
              ${{ secrets.DOCKER_USERNAME }}/mindo-server:latest
